#!/usr/bin/env python3
# Copyright 2026 Local Inference Lab, Inc.
# SPDX-License-Identifier: Apache-2.0
"""Regenerate web/index.html from the design artboard canvas/project/Main.dc.html.

The artboard runs inside the design canvas runtime (support.js). The standalone page swaps in
dc-shim.js and is embedded in the lilmon binary, which serves it with live data from /api/state:

    python3 web/build_standalone.py && cargo build --release && lilmon --serve
"""
from pathlib import Path

WEB = Path(__file__).resolve().parent
SRC = WEB / "canvas" / "project" / "Main.dc.html"
OUT = WEB / "index.html"

HEAD = """<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#050506">
<meta name="description" content="lilmon, the Local Inference Lab monitor: a dashboard for vLLM servers.">
<link rel="icon" href="favicon.svg" type="image/svg+xml">
<style>x-dc{display:none}</style>
<!-- Generated by build_standalone.py from canvas/project/Main.dc.html; edit the artboard, not this file. -->
<script src="dc-shim.js"></script>"""


def replace_once(text: str, old: str, new: str) -> str:
    if old not in text:
        raise SystemExit(f"build_standalone: expected to find {old!r} in {SRC.name}")
    return text.replace(old, new, 1)


def main() -> None:
    html = SRC.read_text()
    html = replace_once(html, '<script src="./support.js"></script>', HEAD)
    html = replace_once(
        html,
        '<html lang="en">\n<head>',
        '<html lang="en">\n<!-- Copyright 2026 Local Inference Lab, Inc. SPDX-License-Identifier: Apache-2.0 -->\n<head>',
    )
    OUT.write_text(html)
    print(f"wrote {OUT.relative_to(WEB.parent)}")


if __name__ == "__main__":
    main()
